### ISSUE TITLE
📈🎨 Visualise all-students progression week-to-week

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#396]
As a user, I want to see the overall progression of all students taking a course.

This data needs to clearly show two dimensions:

1. Growth of amount of students taking the class
2. Progression of the students taking the class (by milestone/chapter) 

Both are measured over time.

### Functional assessment

The proposed visualisation is as below:

![image](https://user-images.githubusercontent.com/3729474/229517184-ac45594a-ced9-4c64-8272-e0bc4a6fd300.png)

You can clearly see those two dimensions at work here. Whereas the height of the graph shows the number of students taking the course, the colours internal to the bar chart show how quickly students are progressing through the course.

### Technical assessment

The data should track all users of a specific organisation.
Progression/milestone data should be fetched from the "chapter" property on the Story object.
The progression should be monitored for each organisation on a nightly basis. 

### TODO's

Most of this logic has already been implemented on the #feature/mne branch. Some todos remain

- [ ] Optimise data use of the calculation by re-using the stories collection.
- [ ] After first analysis, only calculate progress of the last week and store the previous progressions in the DB (save a lot of computing power/monnies)
- [ ] Run a nightly cron job to calculate the week's results and store the results
- [ ] Allow manual re-calculation of the whole graph
- [ ] Implement proper state layer (right now runs off the component)
