### ISSUE TITLE
📈🎨 Visualise student progression by class

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa#397]
As a user, I want to see the overall progression of all students **of a specific class which are** taking a course.

This visualisation is the same as #395 and most code should this be re-used!

### Functional assessment

The proposed visualisation is as below:

<img width="714" alt="image" src="https://user-images.githubusercontent.com/3729474/229520052-ae9385e3-1f14-4f23-8f20-cd1fe9facb95.png">

When selecting one of the classrooms, the chart should be scoped to only the students in that specific classroom.

### Technical assessment

The data should track all users of a specific organisation.
Progression/milestone data should be fetched from the "chapter" property on the Story object.
The progression should be monitored for each organisation on a nightly basis. 

### TODO's

Most of this logic has already been implemented on the #feature/mne branch. Some todos remain

- [ ] Extend algorithm of #396 to also seperate the data by class (preferrably in one single calculation!!) 
- [ ] Run a nightly cron job to calculate the week's results per class and store the results (preferrably one CRON which does both!)
- [ ] Allow manual re-calculation of the whole graph
- [ ] Implement proper state layer (right now runs off the component)
