### ISSUE TITLE
:memo: Add Coding Style Guide in docs

### ISSUE THREAD

**Issue by pmutua** [italanta/elewa#41]
Add coding style guide in the docs section as a guide document that has information about various coding standards to be followed when writing code.

**TODO**
- [x] Add TypeScript style guide
- [x] Add Angular style guide 
- [ ] Document Instructions of using global _scss_ variables
