### ISSUE TITLE
 🧰  Add Hover Tooltip to Delete Icon of Connections

### ISSUE THREAD

**Issue by njoroge-jane** [italanta/elewa#428]
## User stories

As a user I need a way to know how to delete a connection. The delete icon for connections currently lacks any guidance when hovered over. Adding a tooltip that says "double click" on hover will provide this feedback.

---

### Tasks

- [ ] Add a hover tooltip to the delete icon of connections
- [ ] Set the tooltip text to "double click"

### Acceptance Criteria

- [ ] The delete icon of connections has a hover tooltip that says "double click"
- [ ] The tooltip appears when the user hovers over the delete icon

**Comment by Beulah-Matt** [comment]
Working on this
